### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by pwab** [GodotDocMobile/godot_class_reference#1]
Great app. Very fast and has potential to get a daily companion. 👍 
I noticed some minor things and I didn't want to open multiple issues for them:

1. The switch from light to dark theme (and vice versa) needs a lot of loading time on my Android phone. It seems to be stalled a few moments.
2. In the `About` dialog the string 'Press F12' doesn't make lots of sense on a phone. 😄 
3. Every paragraph seems to be indented with a whitespace. This is somehow odd. [See screenshot below]
4. There is no space after a line-break. This leads to very compressed texts which are hard to read (at least for me). [See screenshot below]
5. The text could have a bit more distance to the edges (padding). This would make it more readable.
6. A setting for the text size would be nice.
7. When using the searchbar it could trigger a search immediatly after typing. This would lead to faster search results.
8. Just some nitpicking: As far as I know it's written licence [Br.] or license [Am.] but not lisence as in `godot_lisence` (folder inside the source code) 😅 

![screenshot](https://user-images.githubusercontent.com/19271185/132387454-26fbefac-dd0a-44ab-816c-771a1522ae5c.jpg)

**Comment by fengjiongmax** [comment]
Thank you for creating the very first issue on Github!
1. Switching themes does take a lot of loading time, I think the feeling of stalled can be reduced by adding some loading animation( I didn't make it work by the time I added the switching theme feature), but I'll try again.
2. I can remove that.
3. There are two `tab`s at the start of each paragraph:
https://github.com/godotengine/godot/blob/master/doc/classes/CanvasItem.xml#L7
4. Agreed.
5. Also agreed, are you using a device with a curved edge?
6 & 7. https://github.com/GodotDocMobile/godot_class_reference/projects/1
8. Thank you for pointing that out, I'm not a native English speaker :)

**Comment by fengjiongmax** [comment]
With commit 3b6a26bc5a2562e33362a44b947eaba8e371ac23 , when switching themes, a popup will show and dissapears when finishes loading.

**Comment by pwab** [comment]
> [...] a popup will show and dissapears when finishes loading.

Sounds good. 👍 

> There are two tabs at the start of each paragraph

Yes this comes from the XML formatting, doesn't it? Maybe those could be automatically removed somehow (for example with a regex)?

> Also agreed, are you using a device with a curved edge?

I'm on a [Xiamoi Redmi Note 5](https://en.wikipedia.org/wiki/Redmi_Note_5). So just a standard 6" phone.

**Comment by fengjiongmax** [comment]
> this comes from the XML formatting, doesn't it? 

Yes, I didn't look close enough.
In Chinese, two spaces are required at the start of each paragraph, I mess them up.

3 and 4 is fixed with commit 3e17f07d3be5afaaec1328cf74923013d49c123
![Screenshot_1631881130](https://user-images.githubusercontent.com/5288733/133781489-6f25c0fe-5f4e-4042-af07-3b2b7f787eb6.png)

**Comment by fengjiongmax** [comment]
Now both 6 and 7 are addressed. Screen record files are too big so I can't show them here, even it's heavily compressed.
And will ship with `3.4` docs under version `0.3.0` :yum:.
