### ISSUE TITLE
Support for G4

### ISSUE THREAD

**Issue by MeBadDev** [GodotDocMobile/godot_class_reference#12]

**Comment by fengjiongmax** [comment]
Progress:  document and SVG files are added and some adjustments are made for them ( commit 7adaa0797c945563c45dbd767c04e329a32410ff), but new doc files contain [codeblocks] that have code examples for both gdscript and csharp, which needs a new widget for displaying, working on it.

**Comment by fengjiongmax** [comment]
The new release is uploaded to the App store and Google play, if you are using android and can't wait for the update, please download the apk file from the release page.
