### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by fengjiongmax** [GodotDocMobile/godot_class_reference#14]
Many users from google play have left a review and hope to have a translation.
Initially, I thought the translation was not ready yet, but since more and more users leave similar reviews, we need to make it into the app.

We have two options:
1. Godot engine stores translated text files into the `po` files in the [godotengine/godot-editor-l10n](https://github.com/godotengine/godot-editor-l10n) repo, we can look into the engine and see how it was done, but according to Weblate, translation for most languages are not 10% yet.
2. Use online translation services like DeepL and google translate, both of them require an API key for this purpose, so if we go with this route, we may need users to apply for their own API key and paste the key into the app(which will be stored locally).

**Comment by vmtest888** [comment]
+1

I hope there can be documents in other languages

**Comment by Vladimir15963** [comment]
If you can, why not try both?
Although online translation is better to use, it has certain limitations. Apart from being offline, the translation service may not be available (for example, Google Translate can't access normally in China, so it can only be accelerated through the network or VPN).
（This review comes from machine translation.）

**Comment by Vladimir15963** [comment]
emmmm，我更喜欢用第一种方式解决翻译的问题，因为我希望离线使用，可以两者并存，在设置中选择？
非常感谢这个工具帮助我学习godot

**Comment by Vladimir15963** [comment]
要不先把完成或接近完成的几种语言文档先整上qwq

**Comment by fengjiongmax** [comment]
可以，目前计划先实现第一种做法，第二种是google play上一位用户提出来的，可行性未知，因为需要句子里面可能还有不同的样式和链接，比较难处理。
OK, now I'm planning on implementing the first option, the second option was suggested by a user on Google Play, not sure if it will be easy to implement because, in one sentence, there could be many styles and links.

考虑到有较多的版本，翻译全部加上的话可能会使整个安装包的体积变大，不过到时候可以另外提供一个多语言版本的安装包。
Considering there are many Godot versions, if we include all of the translations may significantly increase the package size, but we can offer another package if that's the case.

**Comment by fengjiongmax** [comment]
I think Godot repository provides translation for class documents at 3.4, you can find a folder `doc/translations`, but no such folder was found before 3.4.

https://github.com/godotengine/godot/commit/8425c589911f8ffc006990f4149859e175ae93a9 in this commit, 10% was the threshold for the class reference document translation, so I'm planning to follow this.

**Comment by fengjiongmax** [comment]
Multi-language support was released under version 0.5.5.
