### ISSUE TITLE
4.1

### ISSUE THREAD

**Issue by rosskarchner** [GodotDocMobile/godot_class_reference#15]
It'd be great to have the 4.1 docs in the app!

**Comment by fengjiongmax** [comment]
Thank you for creating this issue, I haven't looked into Godot's news for a while, so I didn't know 4.1 was released:stuck_out_tongue_winking_eye:.
I'm working on it, for updating the docs, it should be only modifying the Python script and then runs it, but some 4.1 SVG files make flutter throw an exception that I don't know how to catch yet.
I will update my progress on this issue.

**Comment by rosskarchner** [comment]
Great!  According to the blog, 4.2 should be stable in November, so you might want to start looking at that too.

**Comment by fengjiongmax** [comment]
I will put that on my calendar, thanks.
Exception handled with commit a9782e880ac1ee1a1ea2fd4a7b121c6c01d78964.
Now I'm creating releases for here and the app store, Google Play, and closing this issue.
