### ISSUE TITLE
Add dark mode icon for iOS 18

### ISSUE THREAD

**Issue by JMcrafter26** [GodotDocMobile/godot_class_reference#18]
Please add a (truly) dark icon to the app. The app stands out from the rest. A dark icon would make it more appealing.

Thanks

**Comment by fengjiongmax** [comment]
I've modified the icons a little bit, does this one look okay to you?
![image](https://github.com/user-attachments/assets/fb6cf048-fea3-4a1f-92bb-67d03cf2cf30)

**Comment by fengjiongmax** [comment]
For the record, this is what it will look like after the modification:
Dark mode:
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 11 07 08](https://github.com/user-attachments/assets/01f3322b-6fbc-4c61-b202-a3cc0aee073e)
Light mode:
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 11 07 16](https://github.com/user-attachments/assets/703b4b64-945e-4925-ac57-38537103929a)

**Comment by fengjiongmax** [comment]
The update was submitted to Appstore Connect and should be available in a day or two.

**Comment by JMcrafter26** [comment]
The update is live (for me)
Thank you!
