### ISSUE TITLE
Unavailable About button

### ISSUE THREAD

**Issue by Vladimir15963** [GodotDocMobile/godot_class_reference#19]
On the "About" button in the sidebar, it doesn't work. After clicking it, you should jump to the githud page.
I hope the author can fix this small problem, thank you.
![Screenshot_2024-11-09-18-00-52-22_b170625975d5e06938e34ad53e7e9a42.jpg](https://github.com/user-attachments/assets/e3e60820-68e9-4873-b765-a6937e0898ec)

**Comment by fengjiongmax** [comment]
This should be fixed with commit d45f49782278949601f1c1ab7ba76d609c4ef770.

**Comment by fengjiongmax** [comment]
Patches were released under version 0.5.5.
