### ISSUE TITLE
the search feature is not working properly.

### ISSUE THREAD

**Issue by setanarut** [GodotDocMobile/godot_class_reference#8]
the search feature is not working properly.  
![Screenshot_2022-03-14-13-38-43-82_b170625975d5e06938e34ad53e7e9a42](https://user-images.githubusercontent.com/36481442/158156872-184df0a5-49fe-4217-8d25-a866c5f11422.jpg)

**Comment by fengjiongmax** [comment]
This is fixed with commit 981b6b071b013eb958ff0bf205fb788a5775d9c6
![Screenshot_1647340169](https://user-images.githubusercontent.com/5288733/158359021-ca5c77b6-b581-418c-b58a-dec3461d5f92.png)

**Comment by setanarut** [comment]
Sprite should come first when search Sprite. Unexpected order

**Comment by fengjiongmax** [comment]
Make sense, I will sort them before displaying the result.

**Comment by fengjiongmax** [comment]
This is after commit 7b6ae9e5bec477c8fb7a8581ec025a9dda537497
![Screenshot_1647388966](https://user-images.githubusercontent.com/5288733/158491845-cc58681c-f56e-4d07-bf14-aaff1d30c637.png)
![Screenshot_1647388975](https://user-images.githubusercontent.com/5288733/158491851-782309b3-859e-49ed-978c-71caf7342e44.png)

**Comment by fengjiongmax** [comment]
Figured out why there are duplicated `Enum:NodeType.NODE_MIX`, it's fixed with commit 5b6803956a2b92094dae875b65c4a8950ffe1bda

![Screenshot_1647399093](https://user-images.githubusercontent.com/5288733/158507127-af30f954-eb5b-4f8a-9623-04dfe936b042.png)

**Comment by fengjiongmax** [comment]
further improvement with 03bd9928847b7aa8131b8aa474164ff48c7a1290:
![Screenshot_1647404853](https://user-images.githubusercontent.com/5288733/158516815-df09d648-2364-4ab6-87ac-de1469e71435.png)
![Screenshot_1647404846](https://user-images.githubusercontent.com/5288733/158516820-561ded3d-1be3-44a0-9dda-60b85646402e.png)

**Comment by fengjiongmax** [comment]
All changes will be released in version 0.3.7

**Comment by setanarut** [comment]
thanks. also, search results should be monospace. is this possible?

**Comment by fengjiongmax** [comment]
It's done with commit 5554f3f18b1ae99952470ab18e3bd9a2ac6a73d3, I will apply it to next update.
